alias gcc="gcc -Wall -Wwrite-strings -Wshadow -pedantic-errors -fstack-protector-all -Wextra"
alias python=python3
alias fd=fdfind
alias nv=nvim
alias lg=lazygit
alias ip="ip -c"
alias diff="diff --color"
alias t=task
alias hist=history
alias hgrep="history | grep"
alias unixtime="date +%s"
alias gettime="date -d"
alias tempd="cd $(mktemp -d) || echo 'Failed to create temp dir'"
